In [ ]:
import numpy as np

#1.Indicizzazione booleana

#1)
def is_prime(x):

    divisori = 0
    
    for i in range(1,x+1):
        if(x%i==0):
            divisori+=1
    
    if(divisori==2):
        return True
    
    return False

array_primi = np.array([n for n in range(0,21) if is_prime(n)])

#2)
a = array_primi[array_primi > 10]

#3)
primi_pari = array_primi[array_primi % 2 == 0]

#risultati
array_primi, a, primi_pari


(array([ 2,  3,  5,  7, 11, 13, 17, 19]), array([11, 13, 17, 19]), array([2]))

In [ ]:
#2.Operazioni su array

a = np.arange(1,21).reshape(5,4)
#prendo solo la seconda e quarta riga
b = a[[1, 3], :]
#prendo la terza riga
c = a[2, :]

d = a/c

#risultati
a, b, c, d


(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]),
 array([[ 5,  6,  7,  8],
        [13, 14, 15, 16]]),
 array([ 9, 10, 11, 12]),
 array([[0.11111111, 0.2       , 0.27272727, 0.33333333],
        [0.55555556, 0.6       , 0.63636364, 0.66666667],
        [1.        , 1.        , 1.        , 1.        ],
        [1.44444444, 1.4       , 1.36363636, 1.33333333],
        [1.88888889, 1.8       , 1.72727273, 1.66666667]]))

In [ ]:
#3.Seleziona il numero più vicino a 0.5 in un array casuale

#matrice 10x3 con valori casuali
random_arr =np.random.rand(10,3)
#uso il valore assoluto e trovo la distanza di ogni elemento da 0.5, poi seleziono la distanza minima per ogni riga
indici_distanza_minima = np.abs(random_arr-0.5).argmin(axis=1)

righe_arr = np.arange(len(random_arr))
#con lo slicing prendo il valore che corrisponde all'indice della distanza minima
valori_distanza_minima = random_arr[righe_arr, indici_distanza_minima]
#risultati
random_arr, indici_distanza_minima, valori_distanza_minima

(array([[0.03929309, 0.51148819, 0.27224028],
        [0.79095802, 0.27996975, 0.74613984],
        [0.84163907, 0.22211024, 0.26805887],
        [0.21235485, 0.72847384, 0.98114196],
        [0.8632983 , 0.5138204 , 0.51857928],
        [0.75061009, 0.56708351, 0.48224928],
        [0.08011497, 0.34840632, 0.99816128],
        [0.46671373, 0.85962766, 0.87893236],
        [0.70439837, 0.47338878, 0.28669041],
        [0.8258342 , 0.29816212, 0.56952612]]),
 array([1, 1, 2, 1, 1, 2, 1, 0, 1, 2]),
 array([0.51148819, 0.27996975, 0.26805887, 0.72847384, 0.5138204 ,
        0.48224928, 0.34840632, 0.46671373, 0.47338878, 0.56952612]))

In [48]:
#4.Analisi della frequenza cardiaca con numpy

#1)
bpm = np.array([68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70])

#2)
bpm_min = np.min(bpm)

#3)
bpm_max = np.max(bpm)

#4)
bpm_sopra_120 = bpm > 120

def percentuale_osservazioni(array):

    cont = 0

    for n in array:
        if n > 120:
            cont += 1
    
    return cont/len(array) * 100

osservazioni = percentuale_osservazioni(bpm)

#risultati
bpm, bpm_min, bpm_max, bpm_sopra_120, osservazioni

(array([ 68,  65,  77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164,
        163, 162, 100,  90,  97,  72,  60,  70]),
 np.int64(60),
 np.int64(164),
 array([False, False, False, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True, False, False, False,
        False, False, False]),
 52.38095238095239)

In [ ]:
#5.Manipolazione di vettori

#1)
stipendi = np.array([50000, 105250, 55000, 89000])

costo_tot_iniziale = sum(stipendi)

#2)
#aumento stipendio CEO
stipendi = np.where(stipendi == 105250, 105250*1.15 , stipendi)

#3)
#il valore 121037,50 è presente nell'array dopo aver avuto l'aumento

#4)
stipendi = np.array([50000, 105250, 55000, 89000], dtype=float)

stipendi = np.where(stipendi == 105250, 105250*1.15 , stipendi)

#5)
#aumento per l'impiegata che guadagna di meno
stipendi = np.where(stipendi == 50000, 50000*1.20 , stipendi)

#6)
#aumento per gli altri 2 impiegati rimanenti
stipendi = np.where(stipendi == 55000, 55000*1.10 , stipendi)
stipendi = np.where(stipendi == 89000, 89000*1.10 , stipendi)

#7)
costo_tot_finale = sum(stipendi) - costo_tot_iniziale

#risultati
stipendi, costo_tot_iniziale, costo_tot_finale

(array([ 60000. , 121037.5,  60500. ,  97900. ]),
 np.int64(299250),
 np.float64(40187.5))

In [65]:
#6.Valori di Co2

#1)
#carico i dati del file
emissioni = np.loadtxt('emissioni.txt', dtype=float)

#2)
#contatore per segnare i valori >= 18
cont = 0

for value in emissioni:

    if value >= 18:
        cont +=1

media_valori = sum(emissioni)/len(emissioni)

#3)
somma_tot_sopra_la_soglia = 0

for value in emissioni:

    if value >= 18:
        somma_tot_sopra_la_soglia += value

#frazione totale di emissione sopra la soglia
frazione_totale_sopra_la_soglia = somma_tot_sopra_la_soglia/sum(emissioni)

#risultati
emissioni, cont, media_valori, frazione_totale_sopra_la_soglia

(array([15.44, 13.58,  8.35, 11.51,  4.54,  9.53, 11.42,  9.35,  7.16,
         8.97,  5.51, 15.94, 10.96,  4.39, 16.54,  9.65, 14.06, 15.28,
         9.53, 18.64,  6.89, 10.81,  7.44,  8.94, 10.63, 15.5 , 15.21,
         4.53, 10.68, 14.89, 10.86,  4.51, 17.93, 12.28, 12.8 ,  8.06,
        17.35, 15.52,  5.18,  7.37,  4.09, 11.13,  6.43, 12.23, 19.59,
         5.02, 16.44,  9.04, 12.66, 19.84, 13.55,  5.21, 14.54, 13.17,
         7.38,  8.14,  9.09, 10.22,  6.23, 10.  , 12.9 , 11.17,  6.16,
        14.48, 18.78, 16.3 , 10.46, 11.65,  8.37, 11.72, 16.72,  7.63,
         7.85,  4.95, 13.1 ,  7.29, 11.42,  4.68, 15.07, 14.51, 15.9 ,
         5.57, 16.96, 19.84, 18.48,  8.32,  4.89,  5.05,  7.34, 19.16,
        14.96, 17.91,  6.67, 19.52,  7.46,  5.02, 15.55, 17.39,  5.65,
        13.13, 16.49, 17.11, 10.53, 13.24, 16.55, 19.68,  8.56, 18.47,
         9.57, 19.76,  8.27, 12.01, 18.95, 13.75, 11.02,  9.77, 10.69,
         5.72, 13.65, 17.85,  6.35, 12.71, 14.75,  8.39, 12.36, 17.79,
      

In [ ]:
#7.Analisi di una matrice

survey_matrix = np.array([ [25, 40000, 10], [32, 52000, 12], [40, 63000, 14], [29, 47000, 11], [35, 58000, 13] ])

#1)
survey_filtrati = survey_matrix[survey_matrix[:, 2] >= 12]

#2)
redditi = survey_matrix[survey_matrix[:, 2] >= 12, 1]

#3)
media_redditi = redditi.mean()

#risultati
survey_filtrati, redditi, media_redditi
        

(array([[   32, 52000,    12],
        [   40, 63000,    14],
        [   35, 58000,    13]]),
 array([52000, 63000, 58000]),
 np.float64(57666.666666666664))

In [88]:
#8.Rimpiazzare gli outliers

ages = np.array([92, 108, 75, 63, 62, 66, 90, 98, 97, 92, 60, 107, 90, 71, 97, 86, 55, 55,
                 98, 57, 96, 104, 96, 94, 72, 98, 111, 98, 89, 69, 77, 92, 85, 101, 93, 100,
                 90, 101, 96, 98, 999, 87, 106, 86, 108, 55, 67, 65, 68, 59, 67, 72, 57, 79,
                 95, 67, 86, 70, 91, 111, 67, 75, 59, 88, 90, 99, 94, 65, 111, 103, 100, 70,
                 63, 65, 100, 110, 999, 70, 57, 75, 56, 104, 111, 90, 74, 100, 90, 86, 88, 99,
                 58, 103, 88, 103, 64, 96, 105, 89, 83, 65, 100, 62, 73, 105, 83, 105, 58, 96,
                 77, 74, 95, 109, 91, 101, 91, 999, 63, 111, 97, 108, 75, 77, 73, 58, 94, 83,
                 90, 61, 110, 107, 105, 85, 64, 66, 71, 107, 105, 72, 78, 66, 100, 102, 72, 999,
                 74, 68, 73, 72, 90, 93, 99, 55, 92, 83, 58, 71, 89, 75, 98, 87, 999, 78,
                 97, 71, 106, 83, 58, 81, 100, 72, 93, 70, 65, 60, 95, 107, 94, 77, 87, 90,
                 82, 56, 99, 107, 86, 56, 73, 96, 64, 69, 64, 92, 57, 104, 110, 69, 66, 68,
                 84, 89, 72, 80, 55, 75, 87, 57, 106, 69, 66, 62, 102, 76, 111, 999, 96, 83,
                 84, 61, 102, 63, 107, 63, 76, 58, 83, 58, 61, 71, 77, 90, 74, 100, 103, 74,
                 92, 102, 63, 87, 93, 61, 63, 86, 74, 98, 64, 999, 78, 95, 84, 81, 107, 85,
                 79, 82, 89, 65, 107, 57, 74, 77, 97, 92, 58, 96, 105, 60, 55, 74, 57, 80,
                 62, 85, 87, 62, 999, 71, 74, 70, 97, 59, 82, 96, 105, 70, 89, 105, 60, 70,
                 87, 999, 64, 108, 107, 104, 85, 95, 108, 74, 64, 97, 89, 88, 79, 67, 81, 92,
                 63, 80, 76, 94, 104, 67, 73, 61, 99, 96, 68, 90, 86, 79, 85, 111, 75, 98,
                 81, 111, 108, 103, 85, 72, 108, 102, 999, 64, 107, 112, 66, 93, 89, 78, 66, 92,
                 63, 101, 92, 64, 72, 56, 71, 64, 87, 78, 107, 85, 109, 95, 69, 111, 64, 72,
                 55, 66, 99, 57, 78, 55, 58, 90, 88, 71, 90, 103, 92, 98, 67, 97, 77, 68,
                 77, 59, 78, 69, 77, 81, 61, 99, 999, 85, 78, 104, 97, 95, 74, 70, 69, 83,
                 68, 68, 77, 60, 85, 82, 93, 66, 71, 62, 64, 107, 999, 65, 78, 59, 83, 67,
                 108,  58,  95, 106,  83,  79,  67,  59,  96,  90,  55,  55,  96, 109,  82,  55, 101,  58,
                 97, 77, 60, 81, 999, 81, 75, 100, 66, 65, 105, 94, 101, 56, 999, 59, 105, 59,
                 93, 56, 104, 74, 81, 62, 76, 65, 107, 60, 107, 98, 77, 86, 83, 104, 74, 69,
                 97, 80, 91, 56, 108, 87, 65, 91, 93, 60, 91, 110, 107, 88, 96, 70, 60, 99,
                 66, 91, 107, 65, 81, 109, 84, 106, 80, 92, 78, 84, 91, 59])

#converto in float per poter poi assegnare np.nan
ages = np.array(ages, dtype=float)

ages[ages == 999] = np.nan

age_max = max(ages)

#risultati
age_max

np.float64(112.0)

In [89]:
#9.Generazione random di storie

lista_parole = [
    'INSEDIAMENTO', 'SEPARAZIONE', 'DIFFERENZA', 'APPLICAZIONE', 'ATTEGGIAMENTO', 'VERDURA', 'IMPERO', 'RICEVIMENTO',
    'IGNORANZA', 'BIOGRAFIA', 'VISIONE', 'AGENTE DI POLIZIA', 'PROVA', 'PRESTAZIONE', 'PRESENTAZIONE', 'PARENTE',
    'GIUSTIFICAZIONE', 'FILOSOFIA', 'DIREZIONE', 'BENEFICIARIO', 'BATTERIA', 'CERIMONIA', 'AGONIA', 'RECUPERO',
    'ALFABETIZZAZIONE', 'CONSEGNA', 'SERBATOIO', 'VOLONTARIO', 'DEPOSITO', 'BIRILLO DA BOWLING', 'NEMICO', 'ANNUNCIO',
    'CARAMELLA ZUCCHERATA', 'FULMINE', 'PALLONCINO', 'COPERTA', 'SCOPERTA', 'PENALITÀ', 'GENERALE', 'ALPACA',
    'VANTAGGIO', 'HOT DOG', 'ABITO', 'MATEMATICA', 'VARIANTE'
]

parola = np.random.choice(lista_parole, size=5, replace=True)

storia = f"""In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico {parola[0]} che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il {parola[1]} come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "{parola[2]}".
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un {parola[3]}.
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza {parola[4]}!" Ci fu grande gioia e celebrazione."""

#risultato
storia



'In epoche passate, viveva una donna saggia che era molto orgogliosa dell\'antico SEPARAZIONE che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il NEMICO come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "ANNUNCIO".\nRadunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un PRESENTAZIONE.\nNel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.\nCon un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza VARIANTE!" Ci fu grande gioia e celebrazione.'